export default {
  signUpPage: {
    CreateAccountButton: '#CreateAccountButtonId',
    createIndividualAccountButton: '#CreateIndividualAccountId',
    EmailCodeInput: '#EmailCodeInputId',
    EmailConfirmButton: '#EmailConfirmButtonId',
    emailErrorMessage: '#EmailInputId-helper-text',
    emailInput: '#EmailInputId',
    firstNameErrorMessage: '#FirstNameInputId-helper-text',
    firstNameInput: '#FirstNameInputId',
    haveAnAccountLink: '[href="/auth/signin"]',
    idrLogo: '[src*="IDRLogoWhite.svg"]',
    lastNameErrorMessage: '#LastNameInputId-helper-text',
    lastNameInput: '#LastNameInputId',
    passwordErrorMessage: '#component-error-text',
    passwordInput: '#outlined-adornment-password',
    selectCountryDropdown: '#mui-component-select-country_id',
    signUpButton: '#SignupLinkId',
    termsAndConditionsCheckBox: 'I agree with the Terms and Conditions.',
  },
  myInformation: {
    clientAccountType: '#IDV_clientAccountTypeId',
    countryOfCitizenshipDropdown: '#IDV_CountryOfCitizenshipId',
    genderDropdown: '#IDV_GenderId',
    middleNameInput: '#IDV_MiddleNameId',
    SalutationInput: '#IDV_SalutationId',
    salutationItemMr: '#IDV_SalutationItemMr',
  },
  additionalInfo: {
    cityName: '#IDV_CityId',
    countryOfResidence: '#IDV_AddressCountryId',
    dateOfBirth: '#IDV_DOBDatePickerId',
    firstStreetName: '#IDV_Street1Id',
    phoneNumber: '#IDV_PhoneNumberId',
    region: '#IDV_RegionId',
    secondStreetName: '#IDV_Street2Id',
    taxID: '#IDV_TaxID',
    zipCode: '#IDV_ZipId',
  },
  noticeAddress: {
    country: '#IDV_NoticesCountryId',
    differentNoticeAddress: '#IDV_NoticesAddressId',
    nCityName: '#IDV_NoticesCityId',
    nFirstStreetName: '#IDV_NoticesStreet1Id',
    nRegion: '#IDV_NoticesRegionId',
    nSecondStreetName: '#IDV_NoticesStreet2Id',
    nZipCode: '#IDV_NoticesZipId',
  },
  uploadDoc: {
    documentType: '#IDV_IdDoc',
    idExpiresOnDatePicker: '#IDV_IDExpiresOnDatePickerId',
    inputIDFrontDrop: '[id*="InputIDFrontDrop"]',
    issuingCountry: '#IDV_IssuingCountryId',
  },
  shared: {
    saveFormButton: '#ContactSaveButtonId',
    selectFirstOption: '[id*="option-0"]',
    saveAndContinueButton: '#EntityInfo_SaveButtonId',
  },
  dashboard: {
    custodianInput: '#IDV_CustodianNameAutoCompleteId',
    accountHolderName: '#IDV_CustodianAccountNameId',
    accountNumber: '#IDV_CustodianAccountNumber',
    forFurtherCredit: '#IDV_CustodianFOrFurtherCredit',
    saveAndContinueButton:'#CustodialAgreementSaveButtonId',
    portalDisclosureAgreementButton: '#ConfirmButton2',
  },
};
