export default {
  signUpPage: {
    CreateAccountButton: '#CreateAccountButtonId',
    createIndividualAccountButton: '#CreateIndividualAccountId',
    EmailCodeInput: '#EmailCodeInputId',
    EmailConfirmButton: '#EmailConfirmButtonId',
    emailErrorMessage: '#EmailInputId-helper-text',
    emailInput: '#EmailInputId',
    firstNameErrorMessage: '#FirstNameInputId-helper-text',
    firstNameInput: '#FirstNameInputId',
    haveAnAccountLink: '[href="/auth/signin"]',
    idrLogo: '[src*="IDRLogoWhite.svg"]',
    lastNameErrorMessage: '#LastNameInputId-helper-text',
    lastNameInput: '#LastNameInputId',
    passwordErrorMessage: '#component-error-text',
    passwordInput: '#outlined-adornment-password',
    selectCountryDropdown: '#mui-component-select-country_id',
    signUpButton: '#SignupLinkId',
    termsAndConditionsCheckBox: 'I agree with the Terms and Conditions.',
  },
  myInformation: {
    clientAccountType: '#IDV_clientAccountTypeId',
    SalutationInput: '#IDV_SalutationId',
    middleNameInput: '#IDV_MiddleNameId',
    genderDropdown: '#IDV_GenderId',
    salutationItemMr: '#IDV_SalutationItemMr',
    countryOfCitizenshipDropdown: '#IDV_CountryOfCitizenshipId',
  },
  additionalInfo: {
    countryOfResidence: '#IDV_AddressCountryId',
    firstStreetName: '#IDV_Street1Id',
    secondStreetName: '#IDV_Street2Id',
    cityName: '#IDV_CityId',
    region: '#IDV_RegionId',
    zipCode: '#IDV_ZipId',
    taxID: '#IDV_TaxID',
    dateOfBirth: '#IDV_DOBDatePickerId',
    phoneNumber: '#IDV_PhoneNumberId',
  },
  noticeAddress: {
    differentNoticeAddress: '#IDV_NoticesAddressId',
    country: '#IDV_NoticesCountryId',
    nFirstStreetName: '#IDV_NoticesStreet1Id',
    nSecondStreetName: '#IDV_NoticesStreet2Id',
    nCityName: '#IDV_NoticesCityId',
    nRegion: '#IDV_NoticesRegionId',
    nZipCode: '#IDV_NoticesZipId',
  },
  uploadDoc: {
    documentType: '#IDV_IdDoc',
    idExpiresOnDatePicker:"#IDV_IDExpiresOnDatePickerId",
    issuingCountry:"#IDV_IssuingCountryId",
    inputIDFrontDrop: '[id*="InputIDFrontDrop"]',
  },
};
